root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp\\task-vault.exe"
  cmd = "templ generate; go build -o tmp\\task-vault.exe ./cmd/main.go"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "web"]
  log = "build-errors.log"
  send_interrupt = false

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true